### ISSUE TITLE
Updates in provisional and labelling station metadata do not always percolate through

### ISSUE THREAD

**Issue by eee-ea** [ICOS-Carbon-Portal/meta#13]
Updates in provisional and labeling station metadata do not always percolate through in map app and labeling interface. Had to delete the old full name before it was shown in map and labeling app

**Comment by mirzov** [comment]
This is due to a design of the labeling app. If a PI has used it and saved stations metadata, then the labeling interface makes a copy of station's metadata, and uses that copy afterwards. The stations map uses only the provisional stations database. Changes to the latter may not be immediately visible on the map due to SPARQL query caching (up to 1 hour).
