### ISSUE TITLE
station map projection / boundary

### ISSUE THREAD

**Issue by claudiodonofrio** [ICOS-Carbon-Portal/meta#99]
ICOS has stations in for example, La Reunion, South America etc.
they are not shown in the map. Please add the possibility to zoom out to the world
or change the projection. We had the same issue about a year ago, and the map was updated then, 
but the changes were lost somewhere?
https://static.icos-cp.eu/share/stationsproj

**Comment by roger-groth** [comment]
The map can handle a few reference systems. Provide an illegal srid to see them: https://static.icos-cp.eu/share/stationsproj/?srid=what.

These are supported:
https://epsg.io/3006
https://epsg.io/3035 (default)
https://epsg.io/4326
https://epsg.io/3857

So if you want to see the world, provide srid 4326 or 3857. The latter is normally used in web maps.

https://static.icos-cp.eu/share/stationsproj/?srid=3857 will center automatically but you can also specify that together with zoom level: https://static.icos-cp.eu/share/stationsproj/?srid=3857&center=0,0&zoom=2.352322105929321. Zoom and pan in the map until you have the extent you want and save the URL.

When the stations map was created, there was a request to use the European reference system so that is why it's the default.

**Comment by claudiodonofrio** [comment]
Not sure why this is closed
1. srid 3006 does not work (the others work and i can see the 'world' map)
2. I know we had this discussion before , and last time you guys added a 'menu' to switch between 'europe' and the 'world' (like the one where you select the map type)
3. Are we really going to tell users which are visiting our website, they should manually insert `srid=4326`  to see a *complete* list of all ICOS stations ?

**Comment by roger-groth** [comment]
1. 3006 is Sweden only. Perhaps it requires a center point. Not sure. Could be a bug.
2. I don't remember that solution. It sounds like it was created outside of the map application. By Jonathan?
3. I thought this was in the context of our home page. In that case we change the URL.

Where do you want this reference system switch to be available for end users?

**Comment by jonathanthiry** [comment]
I'll recreate a page with this functionality in Drupal.

**Comment by claudiodonofrio** [comment]
hi guys, thanks for looking into this. sorry to be a pain in the back, just trying to improve the user experience and the quality of our website.

**Comment by atverm** [comment]
In fact, this has been a topic of discussion for 4 years already. Mollweide projection would be ideal compared to the Mercator, but it seems to be not supported by the library we use. And for Europe there is regulation that we have to use this Lambert projection to avoid distortion on the size of countries.

Alex

**Comment by mirzov** [comment]
For the future, I would like to propose that among the CP team members, we use issues either for bug reports, or for feature requests that are coming from a corresponding product owner. External users who do not have as good communication channels to us can justifiably submit feature requests as GitHub issues, but from an internal collaborator, this is a misuse, especially when the "feature request" is submitted to a wrong GitHub project, and actually should have been a question on Slack, because the requested feature is already available.
To @claudiodonofrio , regarding why the issue was closed:
- the stations map app actually belongs to project [static](https://github.com/ICOS-Carbon-Portal/static/tree/master/js-projects/stations-ol-proj), 
- its users are web developers or Drupal editors (so [drupal](https://github.com/ICOS-Carbon-Portal/drupal) project probably should have been the place for the issue)
- you received a comprehensive answer to your original request, explaining how to use the functionality

Next time, when you are unsure about why your issue gets closed, please, just ask, do not willfully reopen it. If you have an idea about a new feature, you are welcome to communicate it to the product owner or even directly to the development team first. We have many things on our todo lists, most of them are not represented in GitHub issues, so it could be that your feature is in the pipeline or maybe even already available. Well-written bug reports, on the other hand, are always welcome, but even in that case could be good to ask the team about which project the issue should be submitted to.
Finally, if you are looking for ways of improving the experience of our users, there are more productive ways where you could contribute. For example, preparing GeoJSON for ecosystem sites' geo coverage and making variable metadata for ETC products (no good reason to wait for ETC with this, really).
